### ISSUE TITLE
MMORPG.yaml is missing

### ISSUE THREAD

**Issue by jiabinfan** [CILAB-CT-GAME/RaidEnv#1]
In README.md, "A configuration YAML (MMORPG.yaml) for ML-Agents is provided.", I am wondering where is MMORPG.yaml?

**Comment by KevinJeon** [comment]
Hi, there! The doc is quite old version of our experiment! We should update about it! In the case of yaml.file(If u wanna find playtesting, it is in Experiment/MA/RL_HEURISTIC/configs or Experiment/MA/RL_GENERALIZATION/configs!
